#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitelyi and I am invincible!!!  when receiving a SIGTERM signal.
for ((i=1; i<=5; )); do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
