#!/usr/bin/env bash
# This script loops from 1 to 20 and: displays 4 and then bad luck from China for the 4th loop iteration, displays 9 and then bad luck from Japan for the 9th loop iteration, displays 17 and then bad luck from Italy for the 17th loop iteration
i=1
while [ $i -le 20 ]
do
    echo $i
    i=$((i + 1))
    if [ $i -eq 5 ];
    then
	    echo "bad luck from China"
    elif [ $i -eq 10 ];
    then
	    echo "good luck from Japan"
    elif [ $i -eq 18 ];
    then
	    echo "bad luck from Italy"
    else
	    continue
    fi
done
