#!/usr/bin/env bash
# This script displays: content of the current directory in a list format where only the part of the name after the first dash is displayed.
for file in *
do
    if [[ -f $file ]]; then
        filename=$(basename "$file")
        name_after_dash=${filename#*-}
        echo "$name_after_dash"
    fi
done
