#!/usr/bin/env bash
#This script gives you information about the school file.
if [[ -f school ]]; then
	echo "school file exists"
	if [[ -s school ]]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	echo "school is a regular file"
elif [[ -d school ]]; then
	echo "school file exists"
	echo "school file is not empty"
else
	echo "school file does not exist"
fi
